openapi: 3.0.3
info:
  title: SIGLAD - Auth API
  version: "1.0.0"
paths:
  /api/auth/login:
    post:
      summary: Iniciar sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string, format: email }
                password: { type: string, minLength: 8 }
      responses:
        "200": { description: OK }
        "401": { description: Credenciales inválidas }
        "403": { description: Usuario inactivo }
  /api/auth/me:
    get:
      summary: Datos del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        "200": { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
